name: zentro
description: Takeaway application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  get: ^4.6.5
  objectbox: ^1.7.2
  objectbox_flutter_libs: any
  flutter_screenutil: ^5.6.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  flutter_svg: ^1.1.6
  path_provider: ^2.0.11
  path: ^1.8.2
  country_picker: ^2.0.19
  pinput: ^2.2.21
  email_validator: ^2.1.17
  geolocator: ^9.0.2
  geocoding: ^2.0.5
  flutter_layout_grid: ^2.0.1
  firebase_storage: ^11.0.10
  flutter_cache_manager: ^3.3.0
  shimmer: ^2.0.0
  firebase_app_check: ^0.1.2
  flutter_rating_bar: ^4.0.1
  badges: ^3.0.2
  collection: ^1.17.0
  dotted_border: ^2.0.0+3
  visibility_detector: ^0.4.0+2
  flutter_dotenv: ^5.0.2
  firebase_remote_config: ^4.0.0
  firebase_analytics: ^10.2.0
  razorpay_flutter: ^1.3.4
  flutter_stripe: ^9.0.0+1
  http: ^0.13.5
  pay: ^1.1.0
  uuid: ^3.0.7
  lottie: ^2.3.1
  flutter_staggered_animations: ^1.1.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  objectbox_generator: any
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.0
  flutter_native_splash: ^2.2.19

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/.env
    - assets/lottie/

objectbox:
  output_dir: generated

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/Zentro.png"
  min_sdk_android: 24

flutter_native_splash:
  color: "#e9d6b9"
