name: zentro
description: Takeaway application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  get: ^4.6.5
  objectbox: ^1.7.0
  objectbox_flutter_libs: any
  flutter_screenutil: ^5.6.0
  firebase_auth: ^4.2.1
  cloud_firestore: ^4.2.0
  flutter_svg: ^1.1.6
  path_provider: ^2.0.11
  path: ^1.8.2
  country_picker: ^2.0.19
  pinput: ^2.2.21
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  objectbox_generator: any

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

objectbox:
  output_dir: generated
